controller_list:
  - name: fake_Arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
  - name: fake_Gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - link_04__grip_l
      - link_04__grip_r
initial:  # Define initial robot poses per group
  - group: Arm
    pose: Straight_Up
  - group: Gripper
    pose: Open